# Generated by Django 5.0 on 2023-12-27 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_remove_book_release_date_remove_book_release_flag_and_more"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartunit",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.book",
                verbose_name="書籍",
            ),
        ),
        migrations.AlterField(
            model_name="cartunit",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="購入数",
            ),
        ),
    ]
