# Generated by Django 5.0 on 2023-12-25 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_goodsgroup_remove_book_category_remove_book_comment_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
