# Generated by Django 5.0 on 2023-12-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_delete_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリー名")),
            ],
        ),
    ]
