# Generated by Django 5.0 on 2023-12-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="book",
            name="release_flag",
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.CharField(max_length=500, verbose_name="説明"),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=100, null=True, verbose_name="書籍名"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.PositiveIntegerField(verbose_name="価格"),
        ),
    ]
