# Generated by Django 5.0 on 2023-12-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_groups_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_received_email",
            field=models.BooleanField(default=True, verbose_name="お問い合わせメールを受け取るか"),
        ),
    ]
