# Generated by Django 5.0 on 2023-12-29 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_customuser_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="cart",
            new_name="cart_id",
        ),
    ]
