# Generated by Django 5.0 on 2023-12-29 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_rename_cart_customuser_cart_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="cart_id",
            new_name="cart",
        ),
    ]
