# Generated by Django 5.0 on 2023-12-29 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_rename_cart_id_customuser_cart"),
        ("store", "0002_alter_cartunit_book_alter_cartunit_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="cart",
        ),
        migrations.AddField(
            model_name="customuser",
            name="cart_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.cart",
            ),
        ),
    ]
