# Generated by Django 5.0 on 2023-12-31 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_rename_customuser_user"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("store", "0002_alter_cartunit_book_alter_cartunit_quantity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CustomUser",
        ),
    ]
