# Generated by Django 5.0 on 2024-01-01 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_rename_user_customuser"),
        ("store", "0002_alter_cartunit_book_alter_cartunit_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=64, verbose_name="住所"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cart",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.cart",
                verbose_name="カート",
            ),
        ),
    ]
